package com.sph.hyu.batch.report.gamrir.repository;

import com.sph.hyu.batch.report.gamrir.domain.TbRptMtSupervisionAssetInput;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;
import org.springframework.data.repository.query.Param;

import java.util.List;
import java.util.Map;
import java.util.UUID;

public interface SupervisionAssetInputRepository extends JpaRepository<TbRptMtSupervisionAssetInput, Integer> {

    /** 장비 투입 현황 (금일/전일 대수 누적) — 검증된 원본 SQL 재사용 */
    String GET_EQUIPMENT_MANAGEMENT = ""
            + " WITH combined_data AS ( "
            + "     SELECT res.prj_id "
            + "           ,res.asset_type "
            + "           ,res.asset_id "
            + "           ,res.asset_nm "
            + "           ,CAST(res.asset_standard AS VARCHAR) AS asset_standard "
            + "           ,res.event_date "
            + "           ,res.yesterday_count "
            + "           ,res.today_count "
            + "       FROM ("
            + "         WITH asset_info AS ( "
            + "             SELECT asset_id "
            + "               FROM ( "
            + "                 SELECT prj_id, gps_date, asset_type, asset_id "
            + "                   FROM iot.tb_iot_it_tracking_load "
            + "                 UNION ALL "
            + "                 SELECT prj_id, gps_date, asset_type, asset_id "
            + "                   FROM iot.tb_iot_it_tracking_load_earthwork "
            + "               ) load "
            + "              WHERE 1 = 1 "
            + "                AND prj_id = :prjId "
            + "              GROUP BY asset_id "
            + "         ), "
            + "         date_range AS ( "
            + "             SELECT TO_DATE(gps_date, 'YYYYMMDD')\\:\\:date  AS event_date "
            + "               FROM ( "
            + "                 SELECT prj_id, asset_id, gps_date "
            + "                   FROM iot.tb_iot_it_tracking_load "
            + "                 UNION ALL "
            + "                 SELECT prj_id, asset_id, gps_date "
            + "                   FROM iot.tb_iot_it_tracking_load_earthwork "
            + "               ) load "
            + "              WHERE 1 = 1 "
            + "                AND prj_id = :prjId "
            + "              GROUP BY gps_date "
            + "              ORDER BY gps_date "
            + "         ),"
            + "         cumulative_counts AS ( "
            + "             SELECT "
            + "                  tpmp.prj_id "
            + "                 ,tpmp.prj_nm "
            + "                 ,tiith.asset_type "
            + "                 ,tiith.asset_id "
            + "                 ,tiith.asset_nm "
            + "                 ,TO_DATE(tiith.event_date, 'YYYYMMDD') AS event_date "
            + "                 ,COUNT(DISTINCT tiith.asset_id) AS today_count "
            + "                 ,SUM(COUNT(DISTINCT tiith.asset_id)) OVER ( "
            + "                     PARTITION BY tpmp.prj_id, tpmp.prj_nm, tiith.asset_nm "
            + "                     ORDER BY TO_DATE(tiith.event_date, 'YYYYMMDD') "
            + "                     ROWS BETWEEN UNBOUNDED PRECEDING AND 1 PRECEDING "
            + "                  ) AS yesterday_count "
            + "               FROM iot.tb_iot_it_tracking_hist tiith "
            + "               LEFT JOIN "
            + "                 scop.tb_prj_mt_project tpmp ON tiith.prj_id = tpmp.prj_id "
            + "               LEFT JOIN "
            + "                 scop.tb_sys_mt_asset tsma on tiith.asset_id = tsma.asset_id "
            + "              WHERE 1 = 1 "
            + "                AND tpmp.prj_id = :prjId "
            + "                AND tiith.event_date <> '99999999'"
            + "                AND TO_DATE(tiith.event_date, 'YYYYMMDD') >= TO_DATE(TO_CHAR(tpmp.reg_dt, 'YYYYMMDD'), 'YYYYMMDD') "
            + "                AND tiith.event_date >= ( "
            + "                     SELECT min(load.gps_date) "
            + "                       FROM ( "
            + "                         SELECT gps_date "
            + "                           FROM ("
            + "                             SELECT prj_id, asset_id, gps_date "
            + "                               FROM iot.tb_iot_it_tracking_load tiitl "
            + "                             UNION ALL "
            + "                             SELECT prj_id, asset_id, gps_date "
            + "                               FROM iot.tb_iot_it_tracking_load_earthwork tiitle "
            + "                           ) load "
            + "                          WHERE prj_id = :prjId "
            + "                          GROUP BY gps_date"
            + "                       ) load"
            + "                    )"
            + "              GROUP BY tpmp.prj_id, tpmp.prj_nm, tiith.asset_type, tiith.asset_id, tiith.asset_nm, TO_DATE(tiith.event_date, 'YYYYMMDD') "
            + "         ) "
            + "         SELECT "
            + "              tpmp.prj_id "
            + "             ,tpmp.prj_nm "
            + "             ,c.asset_type "
            + "             ,c.asset_id "
            + "             ,c.asset_nm "
            + "             ,case "
            + "                 when c.asset_type = '01' then tpipau.dozer_blade_capacity "
            + "                 when c.asset_type = '02' then tpipau.excavator_bucket_capacity "
            + "                 when c.asset_type = '06' then tpipau.dump_load_capacity "
            + "                 when c.asset_type = '08' then tpipau.grader_blade_width "
            + "                 when c.asset_type = '09' then tpipau.roller_drum_width "
            + "                 when c.asset_type = '17' then 0 "
            + "              end asset_standard "
            + "             ,TO_CHAR(dr.event_date, 'YYYYMMDD') AS event_date "
            + "             ,COALESCE(c.yesterday_count, 0) AS yesterday_count "
            + "             ,COALESCE(c.today_count, 0) AS today_count "
            + "           FROM asset_info at "
            + "          CROSS JOIN "
            + "             date_range dr "
            + "          CROSS JOIN "
            + "             (SELECT DISTINCT prj_id, prj_nm, reg_dt "
            + "                FROM scop.tb_prj_mt_project "
            + "               WHERE prj_id = :prjId) tpmp "
            + "                LEFT JOIN "
            + "                     cumulative_counts c "
            + "                  ON at.asset_id = c.asset_id "
            + "                 AND tpmp.prj_id = c.prj_id "
            + "                 AND dr.event_date = c.event_date "
            + "                LEFT JOIN "
            + "                     scop.tb_prj_it_project_asset_user tpipau "
            + "                  ON tpmp.prj_id = tpipau.prj_id "
            + "                 AND at.asset_id = tpipau.asset_id "
            + "               ORDER BY tpmp.prj_id, dr.event_date, at.asset_id "
            + "             ) res"
            + "          WHERE 1 = 1"
            + "            AND event_date = :eventDate"
            + "            AND asset_nm is not null "
            + "     UNION ALL "
            + "     SELECT trms.prj_id "
            + "           ,trmsai.asset_type "
            + "           ,trmsai.asset_id "
            + "           ,trmsai.asset_nm "
            + "           ,trmsai.asset_standard "
            + "           ,trms.work_date as event_date "
            + "           ,trmsai.yesterday_count "
            + "           ,trmsai.today_count "
            + "       FROM ( "
            + "         SELECT * "
            + "           FROM scop.TB_RPT_MT_SUPERVISION trms "
            + "          WHERE 1 = 1 "
            + "            AND trms.work_date < :eventDate "
            + "            AND trms.prj_id = :prjId "
            + "          ORDER by work_date desc limit 1"
            + "       ) trms "
            + "       LEFT JOIN "
            + "         scop.TB_RPT_MT_SUPERVISION_ASSET_INPUT trmsai "
            + "         ON trms.seq = trmsai.report_id "
            + "      WHERE 1 = 1 "
            + "        AND trmsai.asset_id is not null"
            + "  ) "
            + "  SELECT CAST(prj_id AS VARCHAR) AS prj_id "
            + "          ,asset_type "
            + "          ,CAST(asset_id AS VARCHAR) AS asset_id "
            + "          ,asset_nm "
            + "          ,coalesce(asset_standard, '0') as asset_standard "
            + "          ,event_date "
            + "          ,yesterday_count "
            + "          ,today_count "
            + "      FROM ( "
            + "           SELECT prj_id"
            + "                 ,asset_type"
            + "                 ,asset_id"
            + "                 ,asset_nm"
            + "                 ,asset_standard"
            + "                 ,event_date"
            + "                 ,case "
            + "                   when event_date = :eventDate then yesterday_count "
            + "                   else yesterday_count + today_count "
            + "                  end yesterday_count "
            + "                 ,case "
            + "                   when event_date = :eventDate then 1 "
            + "                   else 0 "
            + "                  end today_count "
            + "                 ,ROW_NUMBER() OVER (PARTITION BY asset_id ORDER BY event_date DESC) AS rn "
            + "             FROM combined_data "
            + "       ) AS ranked_data "
            + "     WHERE rn = 1 "
            + "     ORDER BY event_date DESC, asset_id ";

    @Query(value = GET_EQUIPMENT_MANAGEMENT, nativeQuery = true)
    List<Map<String, Object>> getEquipementManagement(@Param("prjId") UUID prjId,
                                                       @Param("eventDate") String eventDate);
}
